config/routes.rb
Rails.application.routes.draw do 
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get '/cart', to: 'cart#show', as: 'cart_show'
  devise_for :users
  resources :users, controllers: { sessions: 'sessions' }
  #  root 'pages#home'

  resources :categories
  resources :categories, only: [] do
    member do
      get 'products_by_category'
    end
  end
   
  resources :carts

  resources :produits
  
  root 'produits#index'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest', as: :guest_sign_in
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest', as: :admin_guest_sign_in
  end

  #  get 'categories/:category_id/products', to: 'products#products_by_category', as: 'products_by_category'  
  #  resources :categories do
  #   get 'products_by_category', on: :member
  #  end
  
  
# config/routes.rb (pour Rails 2.x)
# get "controller/action/:id", to: "controller#action", as: :cart/add

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderables
    has_many :produits, through: :orderables

    def total
        orderables.to_a.sum { |orderable| orderable.total }
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
   
  end

  def add
    @produit = Produit.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(produit_id: @produit.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity) # Utilisez simplement "quantity" ici
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(produit: @produit, quantity: quantity) # Utilisez simplement "quantity" ici
    end
  
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart',
                                                   partial: 'cart/cart',
                                                   locals: { cart: @cart }),
                              turbo_stream.replace(@produit)]
      end
    end
  end
  

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart })
      end
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_orderables.html.erb
<div class="container">
  <% @cart.orderables.each do |orderable| %>
    <% produit = orderable.produit %>
    <div id="<%= "cart-#{produit.id}" %>" class="card mb-3">
      <div class="card-body">
        <div class="row">
          <div class="col-md-6">
            <h5 class="card-title"><%= produit.nom %></h5>
            <p class="card-text"><%= produit.description %></p>
          </div>
          <div class="col-md-3">
            <p class="card-text"><strong>Price:</strong> <%= produit.prix %></p>
            <%= form_with(url: cart_add_path) do |f| %>
              <%= f.hidden_field :id, value: produit.id %>
              <%= f.number_field :quantity, value: orderable.quantity, min: 0, class: "form-control" %>
              <%= f.submit "Update", class: "btn btn-primary mt-2" %>
            <% end %>
          </div>
          <div class="col-md-3 text-right">
            <p class="card-text"><strong>Total:</strong> <%= orderable.total %></p>
            <%= form_with(url: cart_remove_path) do |f| %>
              <%= f.hidden_field :id, value: orderable.id %>
              <%= f.submit "Remove", class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cart/show.html.erb
<div class ="panier">
<% if @cart.orderables.count > 0 %>
<div class="cart">
<%= render "cart/orderables", cart: @cart %>
</div>
<div class="container">
<div class="row justify-content-center">
  <div class="col-md-8">
    <% if @cart.orderables.present? %>
      <div class="cart">
          <% @cart.orderables.each do |orderable| %>
        
          <% end %>
          <div class="  total-banner bg-success text-white p-2 text-center"style="width:15% ;margin-left:auto;margin-right:auto ;border-radius:5px">
            <h4 class="mb-0"><strong>Total:</strong></h4>
            <h5><%= number_to_currency(@cart.total, unit: "", delimiter: " ", separator: ",", format: "%n %u") %> &euro;</h5>
          </div>
        </div>
        <% end %>
    <% else %>
      <h1 class="text-center">Your cart is empty</h1>
    <% end %>
  </div>
</div>
</div>