config/routes.rb
Rails.application.routes.draw do 
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get '/cart', to: 'cart#show', as: 'cart_show'
  devise_for :users
  resources :users, controllers: { sessions: 'sessions' }
  #  root 'pages#home'

  resources :categories
  resources :categories, only: [] do
    member do
      get 'products_by_category'
    end
  end
   
  resources :carts

  resources :produits
  
  root 'produits#index'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest', as: :guest_sign_in
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest', as: :admin_guest_sign_in
  end

  #  get 'categories/:category_id/products', to: 'products#products_by_category', as: 'products_by_category'  
  #  resources :categories do
  #   get 'products_by_category', on: :member
  #  end
  
  
# config/routes.rb (pour Rails 2.x)
# get "controller/action/:id", to: "controller#action", as: :cart/add

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/produit.rb
class Produit < ApplicationRecord
    has_one_attached :image
    has_many :mesproduits
    has_many :commandes, through: :mesproduits
    belongs_to :categorie

    has_many :orderables
    has_many :carts, through: :orderables
    
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  before_action :set_produit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show , :index]
  # GET /produits or /produits.json
  def index
    @produits = Produit.all

    @q = Produit.ransack(params[:q])
    @produits = @q.result(distinct: true)
  end

  # GET /produits/1 or /produits/1.json
  def show
  end

  # GET /produits/new
  def new
    @produit = Produit.new
  end

  # GET /produits/1/edit
  def edit
  end

  # POST /produits or /produits.json
  def create
    @produit = Produit.new(produit_params)

    respond_to do |format|
      if current_user.admin? && @produit.save
        format.html { redirect_to produit_url(@produit), notice: "Produit créé avec succès." }
        format.json { render :show, status: :created, location: @produit }
      else
        if current_user.admin?
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @produit.errors, status: :unprocessable_entity }
        else
          format.html { redirect_to root_path, alert: "Vous n'êtes pas autorisé à créer des produits." }
          format.json { render json: { error: "Permission denied" }, status: :forbidden }
        end
      end
    end
  end
  

  # PATCH/PUT /produits/1 or /produits/1.json
  def update
    respond_to do |format|
      if @produit.update(produit_params)
        format.html { redirect_to produit_url(@produit), notice: "Produit modifié avec succes." }
        format.json { render :show, status: :ok, location: @produit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produits/1 or /produits/1.json
  def destroy
    @produit.destroy

    respond_to do |format|
      format.html { redirect_to produits_url, notice: "Produit supprimé avec succes." }
      format.json { head :no_content }
    end
  end

# Pour afficher les produits d'une categorie
# def products_by_category
#   @category = Categorie.find(params[:category_id])
#   @produitss = @category.produits
# end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produit
      @produit = Produit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produit_params
      params.require(:produit).permit( :nom, :description, :prix, :stock, :categorie_id, :image)
    end
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/views/produits/_form.html.erb
<div class="w-25 p-3 mx-auto">
<%= form_with(model: produit, local: true) do |form| %>
  <% if produit.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(produit.errors.count, "error") %> prohibited this product from being saved:</h4>
      <ul>
        <% produit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :nom, class: "form-label" %>
    <%= form.text_field :nom, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="row mb-3">
    <div class="col-md-6">
      <%= form.label :prix, class: "form-label" %>
      <%= form.text_field :prix, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= form.label :stock, class: "form-label" %>
      <%= form.number_field :stock, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :categorie_id, "Catégorie", class: "form-label" %>
    <%= form.collection_select :categorie_id, Categorie.all, :id, :nom, { prompt: "Sélectionnez une catégorie" }, class: "form-select" %>
  </div>

  <%#= render "image_preview", form: form, produit: produit #%>
  
  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="d-grid">
    <%= form.submit "Enregistrer", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

</div>

app/views/produits/_image_preview.html.erb
<div data-controller="previews">
<div data-controller="previews">
<%= form.label :image, style: "display: block" %>
<%= form.file_field :image,
  direct_upload: true,
  data: { previews_target: "input", action: "change->previews#preview" } %>
<div class="image-container">
  <% if produit.image.attached? %>
    <%= image_tag (produit.image), data: { previews_target: "preview" }, class: "image" %>
  <% else %>
    <%= image_tag "", data: { previews_target: "preview" }, class: "image" %>
  <% end %>
</div>
</div>

app/views/produits/edit.html.erb
<h1>Editing Produit</h1>

<%= render 'form', produit: @produit %>

<%= link_to 'Lire plus', @produit %> |
<%= link_to 'Retour', produits_path %>

app/views/produits/index.html.erb
<% if current_user %>
  <div class="container">
    <div class="nw">
      <% if current_user.admin %>
        <%= link_to 'Nouveau produit', new_produit_path , class: "btn btn-primary nouveau" %>
      <% end %>
    </div>
    <h1 style="margin-left:50px !important">Nouveautés</h1>
    <div class="col-md-6 mx-auto mb-3">
    <%= search_form_for @q, html: { class: "form-inline" } do |f| %>
      <div class="input-group">
        <%= f.search_field :nom_cont, class: "form-control" %>
        <div class="input-group-append">
          <%= f.submit "Rechercher", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>

    
  </div>

  <div class="container toutc">
    <div class="row justify-content-center">
      <% @produits.each do |produit| %>
        <div class="col-md-4">
          <div class="card mb-3 mx-auto d-flex justify-content-center" style="max-width: 245px;">
            <%= link_to produit_path(produit) do %>
              <%= image_tag produit.image, class: "card-img-top", style: "object-fit: cover; height: 246px;" %>
            <% end %>
            <div class="card-body text-center">
              <h5 class="card-title textt"><%= produit.nom %></h5>
              <p class="card-text textt"><%= number_to_currency(produit.prix, unit: "", delimiter: " ", separator: ",", format: "%n %u") %> &euro;</p>
              <div class="addpanier">
                <% if !current_user.admin %>
                  <%= form_with(url: cart_add_path) do |f| %>
                    <%= f.hidden_field :id, value: produit.id %>
                    <%= f.number_field :quantity, value: 0, min: 1 , class: "small-number-field" %>
                    <%= f.submit "Add To Cart", class: "btn btn-primary bb" %>
                  <% end %>
                <% end %>
              </div>
              <%#= link_to 'Lire plus', produit_path(produit), class: 'btn btn-primary' #%>
              <% if current_user.admin %>
                <%= link_to 'Modifier', edit_produit_path(produit) %> | 
                <%= link_to 'Supprimer', produit, method: :delete, data: { confirm: 'Etes vous sûre?' } %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<% else %>
<div class="container mt-4">
<h1 style="text-align:center ;margin-left:auto;margin-right:auto;margin-bottom:30px !important">Bienvenue sur Solutech</h1>
<div class="row">
  <div class="col-md-4">
    <div class="card h-100" >
      <%= image_tag("telechrgements.jpg", alt: "Example Image ", class: "card-img-top img-fluid") %>

      <div class="card-body">
        <h5 class="card-title">Découvrez notre large gamme</h5>
        <p class="card-text">Parcourez notre collection de matériel et d'outils informatiques de qualité pour tous vos besoins.</p>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
    <%= image_tag("premium_photo-1661420059005-46f59e62e478.jpg", alt: "Example Image" , class: "card-img-top img-fluid") %>

      <div class="card-body">
        <h5 class="card-title">Trouvez les meilleures offres</h5>
        <p class="card-text">Profitez de nos offres spéciales et de nos réductions pour acquérir les outils dont vous avez besoin à des prix avantageux.</p>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
    <%= image_tag("photo-1526948531399-320e7e40f0ca.jpg", alt: "Example Image" , class: "card-img-top img-fluid") %>
      <div class="card-body">
        <h5 class="card-title">Inscrivez-vous dès maintenant</h5>
        <p class="card-text">Rejoignez la communauté Solutech en vous inscrivant et bénéficiez d'un accès complet à notre catalogue.</p>
        <%= link_to 'Inscrire', new_user_registration_path, class: "btn btn-primary text-white" %>
      </div>
    </div>
  </div>
</div>
</div>

<div class="text-center mt-2">
<h2>Vous avez déjà un compte ?</h2>
<%= link_to 'Se connecter', new_user_session_path, class: "btn btn-secondary mx-2 text-white mb-3" %>
</div>

<% end %>

app/views/produits/new.html.erb
<h1 style="text-align :center  ">New Produit</h1>

<%= render 'form', produit: @produit %>
<br>

<div class="container ">
<%= link_to 'Retour', produits_path %>
</div>

app/views/produits/products_by_category.html.erb
  <div class="container mx-auto">
  <div class="row justify-content-center">
    <% @produitss.each do |produit| %>
      <div class="col-md-4">
        <div class="card mb-3" style="max-width: 245px;">
          <%= link_to produit_path(produit) do %>
            <%= image_tag produit.image, class: "card-img-top", style: "object-fit: cover; height: 246px;" %>
          <% end %>
          <div class="card-body text-center">
            <h5 class="card-title textt"><%= produit.nom %></h5>
            <p class="card-text textt"><%= number_to_currency(produit.prix, unit: "", delimiter: " ", separator: ",", format: "%n %u") %> &euro;</p>
            <div class="addpanier">
              <% if !current_user.admin %>
                <%= form_with(url: cart_add_path) do |f| %>
                  <%= f.hidden_field :id, value: produit.id %>
                  <%= f.number_field :quantity, value: 0, min: 1 , class: "small-number-field" %>
                  <%= f.submit "Add To Cart", class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </div>
            <%#= link_to 'Lire plus', produit_path(produit), class: 'btn btn-primary' #%>
            <% if current_user.admin %>
              <%= link_to 'Modifier', edit_produit_path(produit) %> | 
              <%= link_to 'Supprimer', produit, method: :delete, data: { confirm: 'Etes vous sûre?' } %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/produits/show.html.erb
<div class="container" style="margin-top:100px;">
<div class="row show">

<div class="col-md-6 colshow ">
<div class="col ">
<%= image_tag (@produit.image), class: "card-img-top", style: "object-fit: cover; height: 246px; width:246px" %>
</div>

<div class="col" style="margin-left:20px ;margin-top:20px; margin-bottom:10px" >

<div class="">
  <strong>Nom:</strong>
  <%= @produit.nom %>
</div>

<div >
  <strong>Description:</strong>
  <%= @produit.description %>
</div>

<div>
<strong>Prix:</strong> 
<%= @produit.prix %>
</div>

<div class"categorie" style= "margin-bottom:10px">
  <strong>Categorie:</strong>
  <%= @produit.categorie.nom %>
</div>

<%= form_with(url: cart_add_path) do |f| %>
  <%= f.hidden_field :id, value: @produit.id %>
  <%= f.number_field :quantity, value: 0, min: 1 , class: "small-number-field" %>
  <%= f.submit "Add To Cart", class: "btn btn-primary", style:"margin-top:-7px ;" %>
<% end %>
<%if current_user.admin %>
<%= link_to 'Modifier', edit_produit_path(@produit) , class:"btn btn-primary mt-2 text-white"%> 
<% end %>

</div>
</div>
</div>

<%= link_to 'Retour', produits_path %>
 </div>