config/routes.rb
Rails.application.routes.draw do 
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get '/cart', to: 'cart#show', as: 'cart_show'
  devise_for :users
  resources :users, controllers: { sessions: 'sessions' }
  #  root 'pages#home'

  resources :categories
  resources :categories, only: [] do
    member do
      get 'products_by_category'
    end
  end
   
  resources :carts

  resources :produits
  
  root 'produits#index'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest', as: :guest_sign_in
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest', as: :admin_guest_sign_in
  end

  #  get 'categories/:category_id/products', to: 'products#products_by_category', as: 'products_by_category'  
  #  resources :categories do
  #   get 'products_by_category', on: :member
  #  end
  
  
# config/routes.rb (pour Rails 2.x)
# get "controller/action/:id", to: "controller#action", as: :cart/add

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show , :index]

  # GET /categories or /categories.json
  def index
    @categories = Categorie.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Categorie.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Categorie.new(category_params)
    # @category.image = params[:category][:image].original_filename if params[:category] && params[:category][:image]
  
    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Categorie créée avec succès." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        # @category.image = params[:category][:image].original_filename if params[:category] && params[:category][:image]
  
        format.html { redirect_to category_url(@category), notice: "Categorie modifiée avec succès." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Categorie supprimée avec succes." }
      format.json { head :no_content }
    end
  end

  def products_by_category
    @category = Categorie.find(params[:id])
    @products = @category.produits
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Categorie.find(params[:id])
    end

   

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:categorie).permit(:nom, :description, :image)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="w-25 p-3 mx-auto">
<%= form_with(model: @category, local: true, html: { enctype: "multipart/form-data" }) do |form| %>
  <% if @category.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :nom, class: "form-label" %>
    <%= form.text_field :nom, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="d-grid">
    <%= form.submit "Enregistrer", class: "btn btn-primary btn-block" %>
  </div>

  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Lire plus', @category %> |
<%= link_to 'Retour', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="new" style="margin-right:10px">
<% if current_user.admin %>
  <%= link_to 'Nouvelle categorie', new_category_path, class: 'btn btn-primary text-white ' %>
<% end %>
</div>
<div class="container ctout" >
  <div class="row " >
    <% @categories.each do |category| %>

      <div class="col-md-4 mx-auto">
      <%= link_to category_path(category) do%>
        <div class="card position-relative">
          <% if category.image.attached? %>
        
            <%= image_tag category.image, class: "card-img-top" %>
          <% end %>
       
          
          <div class="card-img-overlay d-flex flex-column justify-content-end ">
         
            <h2 class="card-title mb-0 text-white"><%= category.nom %></h2>
        
            <p class="card-text text-white mb-2 "><%= category.description %></p>


             <%= link_to 'Voir les produits', products_by_category_category_path(category), class: 'btn btn-primary text-white' %>
           
           
            <% if current_user.admin %>
              <div class="card-footer mx-auto">
                <%= link_to 'Modifier', edit_category_path(category), class: 'btn btn-primary text-white' %>
                <%= link_to 'Supprimer', category, method: :delete, data: { confirm: 'Etes vous sûre?' }, class: 'btn btn-danger text-white' %>
                </div>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

app/views/categories/new.html.erb
<h1 style="text-align: center">New Category</h1>

<%= render 'form', category: @category %>
<div class="container ">
<%= link_to 'Retour', categories_path %>
</div>

app/views/categories/products_by_category.html.erb
<h1 class="mb-5 text-center">Produits de la catégorie <%= @category.nom %></h1>
<div class="container toutc">
  <div class="row justify-content-center">
    <% @products.each do |produit| %>
      <div class="col-md-4">
        <div class="card mb-3 mx-auto d-fley jutify-content-center" style="max-width: 245px;">
          <%= link_to produit_path(produit) do %>
            <%= image_tag produit.image, class: "card-img-top", style: "object-fit: cover; height: 246px;" %>
          <% end %>
          <div class="card-body text-center">
            <h5 class="card-title textt"><%= produit.nom %></h5>
            <p class="card-text textt"><%= number_to_currency(produit.prix, unit: "", delimiter: " ", separator: ",", format: "%n %u") %> &euro;</p>
            <div class="addpanier">
              <% if !current_user.admin %>
                <%= form_with(url: cart_add_path) do |f| %>
                  <%= f.hidden_field :id, value: produit.id %>
                  <%= f.number_field :quantity, value: 0, min: 1 , class: "small-number-field" %>
                  <%= f.submit "Add To Cart", class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </div>
            <%#= link_to 'Lire plus', produit_path(produit), class: 'btn btn-primary' #%>
            <% if current_user.admin %>
              <%= link_to 'Modifier', edit_produit_path(produit) %> | 
              <%= link_to 'Supprimer', produit, method: :delete, data: { confirm: 'Etes vous sûre?' } %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= link_to 'Retour aux catégories', categories_path %>

app/views/categories/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <div class="card w-50 mx-auto">
        <% if @category.image.attached? %>
          <%= image_tag @category.image, class: "card-img-top", style: "object-fit: cover; height: 300px;" %>
        <% end %>
        <div class="card-body">
          <h3 class="card-title"><%= @category.nom %></h3>
          <p class="card-text"><%= @category.description %></p>
        </div>
        <% if current_user.admin %>
          <div class="card-footer ">
          <div class="mx-auto">
            <%= link_to 'Modifier', edit_category_path(@category), class: 'btn btn-primary me-2 text-white ' %>
          </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="mt-3">
    <%= link_to 'Retour', categories_path, class: 'btn btn-secondary text-white' %>
  </div>
</div>