config/routes.rb
Rails.application.routes.draw do 
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get '/cart', to: 'cart#show', as: 'cart_show'
  devise_for :users
  resources :users, controllers: { sessions: 'sessions' }
  #  root 'pages#home'

  resources :categories
  resources :categories, only: [] do
    member do
      get 'products_by_category'
    end
  end
   
  resources :carts

  resources :produits
  
  root 'produits#index'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest', as: :guest_sign_in
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest', as: :admin_guest_sign_in
  end

  #  get 'categories/:category_id/products', to: 'products#products_by_category', as: 'products_by_category'  
  #  resources :categories do
  #   get 'products_by_category', on: :member
  #  end
  
  
# config/routes.rb (pour Rails 2.x)
# get "controller/action/:id", to: "controller#action", as: :cart/add

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solutech</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </head>
 

  <body>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">Solutech</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0 text-white">
        <li class="nav-item">
          <a class="nav-link text-white <%= 'active' if current_page?(produits_path) %>" aria-current="page" href="/produits">Produit</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white <%= 'active' if current_page?(categories_path) %>" href="/categories">Categorie</a>
        </li>
        <% if !current_user %>
        <li class="nav-item"><%= link_to "Utilisateur invité", guest_sign_in_path, method: :post, class: "nav-link text-white" %>
        <li class="nav-item"><%= link_to "Admin invité", admin_guest_sign_in_path, method: :post, class: "nav-link text-white" %>
        <% end %>
        
        <li class="nav-item">
          <a class="nav-link text-white <%= 'active' if current_page?(cart_show_path) %>" href="/cart">Panier</a>
        </li>
        
      </ul>
     
  
      <%= link_to 'Se deconnecter', destroy_user_session_path, method: :delete ,class:"btn btn-danger", style:"color:white"%> 
      
    </div>
    </li>
  </div>
</nav>
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <turbo-frame id="cart"></turbo-frame>
   
    <%= yield %>
  </body>
</html>